### ISSUE TITLE
是否考虑支持 Atom、Sublime 等编辑工具

### ISSUE THREAD

**Issue by wanghaisheng** [vinta/paranoid-auto-spacing#69]

**Comment by vinta** [comment]
這主意不錯，如果有時間的話......

**Comment by wanghaisheng** [comment]
没有技术  不然蛮想试试

**Comment by vinta** [comment]
@wanghaisheng Python（Sublime Text 外掛用的語言）很好入門的吶～

**Comment by wanghaisheng** [comment]
@vinta 工作占了太多业余的时间了。。。

**Comment by laike9m** [comment]
急需 Atom 版本，手动加空格已经要死了_(:3 」∠ )_
希望作者能给力啊

**Comment by 7kfpun** [comment]
之前寫過 gulp 版本的 pangu
https://github.com/7kfpun/gulp-pangu
最近又寫了 atom 的插件
https://github.com/7kfpun/atom-finance / https://github.com/7kfpun/atom-finance-cn

所以就很快的寫完 atom-pangu ...
https://github.com/7kfpun/atom-pangu

**Comment by vinta** [comment]
帥氣！ :+1:

**Comment by laike9m** [comment]
作者请受我一拜！

**Comment by wanghaisheng** [comment]
@7kfpun  赞
